export const styles = {
  container: {
    margin: "20px auto",
    width: "90%",
    maxWidth: "400px",
    textAlign: "center",
    fontFamily: "sans-serif",
    padding: "0 10px",
    backgroundColor: "#121212",
    color: "#ffffff",
    minHeight: "100vh",
  },
  button: {
    padding: "10px 20px",
    cursor: "pointer",
    backgroundColor: "#1e1e1e",
    border: "1px solid #333",
    borderRadius: "4px",
    display: "block",
    width: "100%",
    textAlign: "left",
    maxWidth: "400px",
    margin: "5px auto",
    whiteSpace: "normal",
    wordWrap: "break-word",
    minHeight: "44px",
    color: "#ffffff",
  },
  wrongButton: {
    backgroundColor: "#3d1c1c",
    borderColor: "#cf6679",
    color: "#ff8a8a",
    cursor: "not-allowed",
  },
  input: {
    margin: "5px",
    padding: "10px",
    width: "90%",
    maxWidth: "400px",
    border: "1px solid #333",
    borderRadius: "4px",
    transition: "border-color 0.2s ease",
    boxSizing: "border-box",
    fontSize: "16px",
    backgroundColor: "#1e1e1e",
    color: "#ffffff",
  },
  wrongInput: {
    borderColor: "#cf6679",
    backgroundColor: "#3d1c1c",
  },
  correctAnswer: {
    color: "#81c784",
    fontWeight: "bold",
    margin: "15px 0",
  },
  buttonGroup: {
    display: "flex",
    justifyContent: "center",
    gap: "10px",
    margin: "10px 0",
  },
  showAnswerButton: {
    backgroundColor: "#2d2d2d",
    borderColor: "#404040",
    color: "#b3b3b3",
  },
  answerText: {
    fontSize: "0.9em",
    color: "#81c784",
    marginTop: "5px",
    fontWeight: "normal",
  },
  correctButton: {
    backgroundColor: "#1b3326",
    borderColor: "#4caf50",
    color: "#81c784",
    cursor: "default",
  },
  questionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "15px",
    marginBottom: "20px",
    flexWrap: "wrap",
  },
  skipButton: {
    width: "auto",
    padding: "5px 15px",
    backgroundColor: "#2d2d2d",
    color: "#b3b3b3",
    fontSize: "0.9em",
    margin: "0",
  },
};
